+function($){'use strict';var backdrop='.dropdown-backdrop';var toggle='[data-toggle="dropdown"]';var Dropdown=function(element){$(element).on('click.bs.dropdown',this.toggle);}
Dropdown.VERSION='3.3.7';function getParent($this){var selector=$this.attr('data-target');if(!selector){selector=$this.attr('href');selector=selector&&/#[A-Za-z]/.test(selector)&&selector.replace(/.*(?=#[^\s]*$)/,'');}
var $parent=selector&&$(selector);return $parent&&$parent.length?$parent:$this.parent();}
function clearMenus(e){if(e&&e.which===3)return;$(backdrop).remove();$(toggle).each(function(){var $this=$(this);var $parent=getParent($this);var relatedTarget={relatedTarget:this};if(!$parent.hasClass('open'))return;if(e&&e.type=='click'&&/input|textarea/i.test(e.target.tagName)&&$.contains($parent[0],e.target))return;$parent.trigger(e=$.Event('hide.bs.dropdown',relatedTarget));if(e.isDefaultPrevented())return;$this.attr('aria-expanded','false');$parent.removeClass('open').trigger($.Event('hidden.bs.dropdown',relatedTarget));})}
Dropdown.prototype.toggle=function(e){var $this=$(this);if($this.is('.disabled, :disabled'))return;var $parent=getParent($this);var isActive=$parent.hasClass('open');clearMenus();if(!isActive){if('ontouchstart'in document.documentElement&&!$parent.closest('.navbar-nav').length){$(document.createElement('div')).addClass('dropdown-backdrop').insertAfter($(this)).on('click',clearMenus);}
var relatedTarget={relatedTarget:this};$parent.trigger(e=$.Event('show.bs.dropdown',relatedTarget));if(e.isDefaultPrevented())return;$this.trigger('focus').attr('aria-expanded','true');$parent.toggleClass('open').trigger($.Event('shown.bs.dropdown',relatedTarget));}
return false;}
Dropdown.prototype.keydown=function(e){if(!/(38|40|27|32)/.test(e.which)||/input|textarea/i.test(e.target.tagName))return;var $this=$(this);e.preventDefault();e.stopPropagation();if($this.is('.disabled, :disabled'))return;var $parent=getParent($this);var isActive=$parent.hasClass('open');if(!isActive&&e.which!=27||isActive&&e.which==27){if(e.which==27)$parent.find(toggle).trigger('focus');return $this.trigger('click');}
var desc=' li:not(.disabled):visible a';var $items=$parent.find('.dropdown-menu'+desc);if(!$items.length)return;var index=$items.index(e.target);if(e.which==38&&index>0)index--;if(e.which==40&&index<$items.length-1)index++;if(!~index)index=0;$items.eq(index).trigger('focus');};function Plugin(option){return this.each(function(){var $this=$(this);var data=$this.data('bs.dropdown');if(!data)$this.data('bs.dropdown',(data=new Dropdown(this)));if(typeof option=='string')data[option].call($this);})}
var old=$.fn.dropdown;$.fn.dropdown=Plugin;$.fn.dropdown.Constructor=Dropdown;$.fn.dropdown.noConflict=function(){$.fn.dropdown=old;return this;}
$(document).on('click.bs.dropdown.data-api',clearMenus).on('click.bs.dropdown.data-api','.dropdown form',function(e){e.stopPropagation();}).on('click.bs.dropdown.data-api',toggle,Dropdown.prototype.toggle).on('keydown.bs.dropdown.data-api',toggle,Dropdown.prototype.keydown).on('keydown.bs.dropdown.data-api','.dropdown-menu',Dropdown.prototype.keydown);}(jQuery);$(document).ready(function(){function replaceWithIframe(e,$this){e.preventDefault();var iframe_location=$this.data('iframe'),iframe_width=$this[0].clientWidth||$this.data('width'),iframe_height=$this[0].clientHeight||$this.data('height');var iframe=$('<iframe width="'+iframe_width+'" height="'+iframe_height+'" src="'+iframe_location+'" frameborder="0" allowfullscreen allow="autoplay; encrypted-media"></iframe>');$this.prepend(iframe).delay(200).queue(function(next){$this.find('iframe').nextAll().fadeOut('fast').remove();});};$('.responsive-iframe').click(function(e){replaceWithIframe(e,$(this));});$('#navbar-toggle, #account-toggle').click(function(e){e.preventDefault();(this.classList.contains("is-active")===true)?this.classList.remove("is-active"):this.classList.add("is-active");if(this.id=='navbar-toggle'){$('.account-dropdown').slideUp();$('.account-toggle').removeClass("is-active");$('.navbar-dropdown').slideToggle();}
if(this.id=='account-toggle'){$('.navbar-dropdown').slideUp();$('.navbar-toggle').removeClass("is-active");$('.account-dropdown').slideToggle();}
$('.top-bar').removeClass('bg-down');$('.logo').removeClass('logo-down');$('body, html').toggleClass('no_scroll');});$('.account-dropdown a').click(function(e){var $this=$(this);menu_slide_up().done(function(){window.location=$this.prop('href');});return false;});function menu_slide_up(){return $('.account-dropdown').slideUp().promise();}
var lang_click=false;$('.dropdown').click(function(){if(!lang_click){$('.nav-section').animate({scrollTop:356},400);lang_click=true;}
else{$('.nav-section').animate({scrollTop:0},400);lang_click=false;}});$('.menu-link').click(function(e){$('.navbar-dropdown').slideUp();$('#navbar-toggle').removeClass("is-active");});$(".language-switch").click(function(e){e.preventDefault();e.stopPropagation();var path=$(this)[0].pathname;swithcLanguage(path);});$(".hcc-lang-switch").change(function(e){var path=$(this).val();swithcLanguage(path);});function swithcLanguage(path){var location="/change_language";var next_url=window.location.pathname;var data={"language_code":path.replace(/\//g,''),"next_url":next_url};$.ajax(String(location),{data:JSON.stringify(data),contentType:'application/json',type:'POST',dataType:'json',cache:false,timeout:30000,error:function(){},success:function(response){if(response['next_url']){language_code=data['language_code'];window.location.pathname=response['next_url'];}}});}});function _gaLt(event){var el=event.srcElement||event.target;while(el&&(typeof el.tagName=='undefined'||el.tagName.toLowerCase()!=='a'||!el.href)){el=el.parentNode;}
if(el&&el.href){var filetypes=/\.(zip|rar|tar|gz|exe|dmg|pdf|doc.*|xls.*|ppt.*|pps.*|vcf|txt|csv|rtf|odt|pages|mp3|wav|wma|mov|avi|wmv|mpg|mp4|flv|png|jpg|jpeg|gif|tif|tiff|bmp|svg|eps|ai|psd)$/i;var referrer=document.location.pathname+document.location.search;var open_link=false;if(el.href.match(filetypes)){if(el.className.indexOf("gtm-tracking")>-1){return;}
if(el.href.indexOf(location.host)===-1){dataLayer.push({'event':'uaevent','eventCategory':'Download external file','eventAction':el.href,'eventLabel':referrer});}
else{dataLayer.push({'event':'uaevent','eventCategory':'Download file','eventAction':el.pathname,'eventLabel':referrer});}
open_link=true;}
else if(el.href.indexOf(location.host)===-1){dataLayer.push({'event':'uaevent','eventCategory':'External link','eventAction':el.href,'eventLabel':referrer});open_link=true;}
if(open_link){setTimeout(function(){if(el.target==="_blank"){window.open(el.href);}else{window.location.href=el.href;}}.bind(el),500);event.preventDefault?event.preventDefault():event.returnValue=false;}}}
window.addEventListener?window.addEventListener('load',function(){document.body.addEventListener('click',_gaLt,!1);},!1):window.attachEvent&&window.attachEvent('onload',function(){document.body.attachEvent('onclick',_gaLt);});;(function(window,document){'use strict';var addEvent=(function(){if(document.addEventListener){return function addStandardEventListener(el,eventName,fn){return el.addEventListener(eventName,fn,false);};}
else{return function addIEEventListener(el,eventName,fn){return el.attachEvent('on'+eventName,fn);};}})();var defaultWidths=[96,130,165,200,235,270,304,340,375,410,445,485,520,555,590,625,660,695,736];var getKeys=typeof Object.keys==='function'?Object.keys:function(object){var keys=[],key;for(key in object){keys.push(key);}
return keys;};var applyEach=function(collection,callbackEach){var i=0,length=collection.length,new_collection=[];for(;i<length;i++){new_collection[i]=callbackEach(collection[i],i);}
return new_collection;};var returnFn=function(value){return value;};var noop=function(){};var trueFn=function(){return true;};var debounce=function(fn,wait){var timeout;return function(){var context=this,args=arguments;var later=function(){timeout=null;fn.apply(context,args);};clearTimeout(timeout);timeout=setTimeout(later,wait);};};var Imager=function(elements,opts){var self=this;var doc=document;opts=opts||{};if(elements!==undefined){if(typeof elements==='string'){opts.selector=elements;elements=undefined;}
else if(typeof elements.length==='undefined'){opts=elements;elements=undefined;}}
this.viewportHeight=doc.documentElement.clientHeight;this.selector=!elements?(opts.selector||'.delayed-image-load'):null;this.className=opts.className||'image-replace';this.gif=doc.createElement('img');this.gif.src='data:image/gif;base64,R0lGODlhEAAJAIAAAP///wAAACH5BAEAAAAALAAAAAAQAAkAAAIKhI+py+0Po5yUFQA7';this.gif.className=this.className;this.gif.alt='';this.lazyloadOffset=opts.lazyloadOffset||0;this.scrollDelay=opts.scrollDelay||250;this.onResize=opts.hasOwnProperty('onResize')?opts.onResize:true;this.lazyload=opts.hasOwnProperty('lazyload')?opts.lazyload:false;this.scrolled=false;this.availablePixelRatios=opts.availablePixelRatios||[1,2];this.availableWidths=opts.availableWidths||defaultWidths;this.onImagesReplaced=opts.onImagesReplaced||noop;this.widthsMap={};this.refreshPixelRatio();this.widthInterpolator=opts.widthInterpolator||returnFn;this.gif.removeAttribute('height');this.gif.removeAttribute('width');if(typeof this.availableWidths!=='function'){if(typeof this.availableWidths.length==='number'){this.widthsMap=Imager.createWidthsMap(this.availableWidths,this.widthInterpolator,this.devicePixelRatio);}
else{this.widthsMap=this.availableWidths;this.availableWidths=getKeys(this.availableWidths);}
this.availableWidths=this.availableWidths.sort(function(a,b){return a-b;});}
this.divs=[];this.add(elements||this.selector);this.ready(opts.onReady);setTimeout(function(){self.init();},0);};Imager.prototype.add=function(elementsOrSelector){elementsOrSelector=elementsOrSelector||this.selector;var elements=typeof elementsOrSelector==='string'?document.querySelectorAll(elementsOrSelector):elementsOrSelector;if(elements&&elements.length){var additional=applyEach(elements,returnFn);this.changeDivsToEmptyImages(additional);this.divs=this.divs.concat(additional);}};Imager.prototype.scrollCheck=function(){var self=this;var offscreenImageCount=0;var elements=[];if(this.scrolled){applyEach(this.divs,function(element){if(self.isPlaceholder(element)){++offscreenImageCount;if(self.isThisElementOnScreen(element)){elements.push(element);}}});if(offscreenImageCount===0){window.clearInterval(self.interval);}
this.changeDivsToEmptyImages(elements);this.scrolled=false;}};Imager.prototype.init=function(){var self=this;this.initialized=true;var filterFn=trueFn;if(this.lazyload){this.registerScrollEvent();this.scrolled=true;self.scrollCheck();filterFn=function(element){return self.isPlaceholder(element)===false;};}
else{this.checkImagesNeedReplacing(this.divs);}
if(this.onResize){this.registerResizeEvent(filterFn);}
this.onReady();};Imager.prototype.ready=function(fn){this.onReady=fn||noop;};Imager.prototype.createGif=function(element){if(element.className.match(new RegExp('(^| )'+this.className+'( |$)'))){return element;}
var elementClassName=element.getAttribute('data-class');var elementWidth=element.getAttribute('data-width');var gif=this.gif.cloneNode(false);if(elementWidth){gif.width=elementWidth;gif.setAttribute('data-width',elementWidth);}
gif.className=(elementClassName?elementClassName+' ':'')+this.className;gif.setAttribute('data-src',element.getAttribute('data-src'));gif.setAttribute('alt',element.getAttribute('data-alt')||this.gif.alt);element.parentNode.replaceChild(gif,element);return gif;};Imager.prototype.changeDivsToEmptyImages=function(elements){var self=this;applyEach(elements,function(element,i){elements[i]=self.createGif(element);});if(this.initialized){this.checkImagesNeedReplacing(elements);}};Imager.prototype.isPlaceholder=function(element){return element.src===this.gif.src;};Imager.prototype.isThisElementOnScreen=function(element){var elementOffsetTop=0;var offset=Imager.getPageOffset()+this.lazyloadOffset;if(element.offsetParent){do{elementOffsetTop+=element.offsetTop;}
while(element=element.offsetParent);}
return elementOffsetTop<(this.viewportHeight+offset);};Imager.prototype.checkImagesNeedReplacing=function(images,filterFn){var self=this;filterFn=filterFn||trueFn;if(!this.isResizing){this.isResizing=true;this.refreshPixelRatio();applyEach(images,function(image){if(filterFn(image)){self.replaceImagesBasedOnScreenDimensions(image);}});this.isResizing=false;this.onImagesReplaced(images);}};Imager.prototype.replaceImagesBasedOnScreenDimensions=function(image){var computedWidth,naturalWidth;naturalWidth=Imager.getNaturalWidth(image);computedWidth=typeof this.availableWidths==='function'?this.availableWidths(image):this.determineAppropriateResolution(image);image.width=computedWidth;if(!this.isPlaceholder(image)&&computedWidth<=naturalWidth){return;}
image.src=this.changeImageSrcToUseNewImageDimensions(image.getAttribute('data-src'),computedWidth);image.removeAttribute('width');image.removeAttribute('height');};Imager.prototype.determineAppropriateResolution=function(image){return Imager.getClosestValue(image.getAttribute('data-width')||image.parentNode.clientWidth,this.availableWidths);};Imager.prototype.refreshPixelRatio=function refreshPixelRatio(){this.devicePixelRatio=Imager.getClosestValue(Imager.getPixelRatio(),this.availablePixelRatios);};Imager.prototype.changeImageSrcToUseNewImageDimensions=function(src,selectedWidth){return src.replace(/{width}/g,Imager.transforms.width(selectedWidth,this.widthsMap)).replace(/{pixel_ratio}/g,Imager.transforms.pixelRatio(this.devicePixelRatio));};Imager.getPixelRatio=function getPixelRatio(context){return(context||window)['devicePixelRatio']||1;};Imager.createWidthsMap=function createWidthsMap(widths,interpolator,pixelRatio){var map={},i=widths.length;while(i--){map[widths[i]]=interpolator(widths[i],pixelRatio);}
return map;};Imager.transforms={pixelRatio:function(value){return value===1?'':'-'+value+'x';},width:function(width,map){return map[width]||width;}};Imager.getClosestValue=function getClosestValue(baseValue,candidates){var i=candidates.length,selectedWidth=candidates[i-1];baseValue=parseFloat(baseValue);while(i--){if(baseValue<=candidates[i]){selectedWidth=candidates[i];}}
return selectedWidth;};Imager.prototype.registerResizeEvent=function(filterFn){var self=this;addEvent(window,'resize',debounce(function(){self.checkImagesNeedReplacing(self.divs,filterFn);},100));};Imager.prototype.registerScrollEvent=function(){var self=this;this.scrolled=false;this.interval=window.setInterval(function(){self.scrollCheck();},self.scrollDelay);addEvent(window,'scroll',function(){self.scrolled=true;});addEvent(window,'resize',function(){self.viewportHeight=document.documentElement.clientHeight;self.scrolled=true;});};Imager.getPageOffsetGenerator=function getPageVerticalOffset(testCase){if(testCase){return function(){return window.pageYOffset;};}
else{return function(){return document.documentElement.scrollTop;};}};Imager.getNaturalWidth=(function(){if('naturalWidth'in(new Image())){return function(image){return image.naturalWidth;};}
return function(image){var imageCopy=document.createElement('img');imageCopy.src=image.src;return imageCopy.width;};})();Imager.getPageOffset=Imager.getPageOffsetGenerator(Object.prototype.hasOwnProperty.call(window,'pageYOffset'));Imager.applyEach=applyEach;Imager.addEvent=addEvent;Imager.debounce=debounce;if(typeof module==='object'&&typeof module.exports==='object'){module.exports=exports=Imager;}else if(typeof define==='function'&&define.amd){define(function(){return Imager;});}else if(typeof window==='object'){window.Imager=Imager;}}(window,document));$(document).ready(function(){var $body=$('body');var didScroll;var lastScrollTop=10;var delta=5;var navbarHeight=$('header').outerHeight()+50;$(window).scroll(function(){if($(".account-toggle.collapsed").hasClass("is-active")){return;}else{didScroll=true;}});setInterval(function(){if(didScroll){bg_scroll();didScroll=false;}},200);function bg_scroll(){var st=$(this).scrollTop();var menu_visible=$(".navbar-dropdown").css('display');if(Math.abs(lastScrollTop-st)<=delta)
return;if(st>lastScrollTop&&st>navbarHeight&&menu_visible=='none'){$('.top-bar').removeClass('bg-up').addClass('bg-down');$('.top-bar .logo').removeClass('logo-up').addClass('logo-down');$('.global-ribbon').addClass('hidden');}else{if(st+$(window).height()<$(document).height()){$('.top-bar').removeClass('bg-down').addClass('bg-up');$('.top-bar .logo').removeClass('logo-down').addClass('logo-up');}
$('.global-ribbon').removeClass('hidden');}
lastScrollTop=st;}
if($(".search-header input").length){if($(".search-header input").val().length>0){$(".btn-clear-search").show();}}
$body.on("keypress",".search-header input",function(e){if($(".search-header input").val().length>0){$(".btn-clear-search").show();}
else{$(".btn-clear-search").hide();}});$body.on("click",".btn-clear-search",function(e){$(".btn-clear-search").hide();$(".search-header input").val("");$(".news_page .search-header").submit();return false;});if($('.offer-plans').length>0){var offers_len=$(".offer-plan").length;var offer_width=$(".offer-plan").outerWidth();var offer_margin=($(".offer-wrapper").outerWidth()-$(".offer-plan").outerWidth())/2;var offer_padding=$(".offer-plans").outerWidth()-$(".offer-plans").width();var offer_plan_width=offers_len*(offer_width+(offer_margin*2))+offer_padding;var center_pos=$('.slider-pos .center').offset().left-(offer_padding/2)-offer_margin;var offer_plan=$('.offer-plan');var index=$(".offer-plan").length-1;var touchX;var $target=null;var x;var old_touchX;var start;var speed;var current_offer_pos;var new_position=center_pos-(index*(offer_width+(offer_margin*2)));if($(window).width()<768){$('.offer-plans').on('click','.info-btn',function(e){var target=$(this).find('.info-content');target.toggle();$('.info-content').not(target).hide();});}
if($('.offer-wrapper.disable').length>0){$('.disable .btn-white-starrider').prop('href','');$('.disable .btn-white-starrider').click(function(){return false;});}
if($(window).width()<1100){$('.offer-plans').css('width',offer_plan_width);index=$(".offer-plan").length-1;snap_to_center("",index);}
$(window).resize(function(){center_pos=$('.slider-pos .center').offset().left-(offer_padding/2)-offer_margin;new_position=center_pos-(index*(offer_width+(offer_margin*2)));if($(window).width()<1100){$('.offer-plans').css('width',offer_plan_width);$(".offer-plans").offset({left:new_position});}
else{$('.offer-plans').css('width','100%');$('.offer-plans').css('left','0');}});$body.on('touchstart',".offer-plans",function(e){$target=$('.offer-plans');touchX=e.originalEvent.touches[0].pageX;var $this=$(this);start=true;old_touchX=touchX;current_offer_pos=offer_plan.eq(index).offset().left;touch_start($this,$target,touchX);});$body.on('touchmove','.offer-plans',function(e){touchX=e.originalEvent.touches[0].pageX;var $this=$(this);speed=swipe_speed();if(old_touchX>touchX-5&&old_touchX<touchX+5){start=false;$('body, html').css('overflow-y','auto');return true;}
else if(start==true){touch_move($this,touchX);$('body, html').css('overflow-y','hidden');return false;}});$body.on('touchend','.offer-plans',function(e){var swipe_middle=current_offer_pos+(offer_width/2)-20;var swipe_position=offer_plan.eq(index).offset().left;if(old_touchX>touchX+5&&index<(offers_len-1)){if(speed<-1){index++;}
else if(swipe_position<(swipe_middle*-1)){index++;}}
else if(old_touchX<touchX-5&&index>0){if(speed>1){index--;}
else if(swipe_position>swipe_middle){index--;}}
snap_to_center('',index);dot_navigation(index,center_pos);});}
$('.offer-selected span').click(function(){var $this=$(this);index=$this.index();$this.addClass('selected');$('.offer-plans').addClass('anime');snap_to_center('',index);});function touch_start($this,target,posX){if(target!=$('.offer-plans')){x=posX-($this.offset().left);}else{x=e.offsetX;}}
function touch_move($this,posX){$this=$target;if($this){$this.offset({left:posX-x});}
$('.offer-plans').removeClass('anime');}
var swipe_speed=(function(settings){settings=settings||{};var timer,delta;var old_pos;var new_pos;var delay=settings.delay||1000;function clear(){old_pos=null;delta=0;}
clear();return function(){new_pos=touchX;if(old_pos!=null){delta=new_pos-old_pos;}
old_pos=new_pos;clearTimeout(timer);timer=setTimeout(clear,delay);return delta;};})();function dot_navigation(index,pos){for(index;index<offer_plan.length;index++){pos=pos+(offer_width+(offer_margin*2));if(pos<window){$('.offer-selected span').removeClass('selected');$('.offer-selected span').eq(index).addClass('selected');}}}
function snap_to_center(page,index){var offer_select=$(page+' .offer-selected span');new_position=center_pos-(index*(offer_width+(offer_margin*2)));offer_select.removeClass('selected');offer_select.eq(index).addClass('selected');$('.offer-plans').addClass('anime');$(page+" .offer-plans").offset({left:new_position});}});(function($,window){var $cookieContainer=$('.cookie-container'),localStorageKey='CookieBarConfirm';if(typeof localStorage==='object'){try{if(localStorage.getItem(localStorageKey)!=='1'){$cookieContainer.slideToggle();}
$cookieContainer.find('.close').on('click',function(e){e.preventDefault();e.stopPropagation();if(localStorage.getItem(localStorageKey)!=='1'){$cookieContainer.slideToggle();localStorage.setItem(localStorageKey,1);localStorage.close='1';}});}catch(e){}}})(jQuery,this);(function($,window){var ua=window.navigator.userAgent,msie=ua.indexOf("MSIE "),trident=ua.indexOf("Trident"),edge=ua.indexOf("Edge/");if(msie>0||trident>0||edge>0){$('head').append('<link rel="stylesheet" href="/css/ie.css" type="text/css" />');}})(jQuery,this);var populate_popup=function(response){if(response){$('#age_form').hide();$('#message_gate').show();$('#message_gate').append("<p>"+response['message']+"</p>");$('#message_gate').append("<a class='btn btn-action-raf'>"+response['link_text']+"</a>");if(response['redirect_link']){$('#message_gate a').attr('href',response['redirect_link']);}}};$('#age_gate').on('click','.close-form, .lightbox-bg',function(e){if(!$(e.target).is('.lightbox-wrapper *, .lightbox-wrapper')){$('#age_gate').hide();}});$('body').on('click','.btn-age-verify',function(e){e.preventDefault();e.stopPropagation();var $form=$('#age_verify');var data=$form.serializeArray();var indexed_array={};$.map(data,function(n,i){indexed_array[n['name']]=n['value'];});indexed_array['action']=$form.data('action');if($('#year').val()>0&&$('#month').val()>0&&$('#day').val()>0){$('.btn-age-verify').prop('disabled',true);age_gate(indexed_array);}});var attach_age_gate_event=function(action){if(action==="support_form"){$('.close-form').remove();$('#age_gate').off('click','.close-form, .lightbox-bg');}};var age_gate=function(data){$.ajax("age_gate/verify",{data:JSON.stringify(data),contentType:'application/json',type:'POST',dataType:'json',cache:false,timeout:30000,error:function(response){$("#age_verify").find(".error-label").text(response.responseJSON['day']);$('.btn-age-verify').prop('disabled',false);},success:function(response){if(response['submit_form']){$("#age_verify").submit();}
else if(response['next_url']){window.location.pathname=response['next_url'];}
else{populate_popup(response);$("#age_gate").show();}}});};var get_popup_data=function(action){$.ajax("/"+language_code+"/age_gate/data",{data:{"action":action},type:"GET",cache:false,success:function(response){if(!response['submit_form']){populate_popup(response);attach_age_gate_event(action);$("#age_gate").show();}
else if(response['next_url']){$("#age_gate").hide();window.location.href=response['next_url'];}}});};var age_gate_check=function(action){$.ajax("/"+language_code+"/age_gate/widget",{data:{"action":action},type:'GET',cache:false,error:function(data){},success:function(response){$("#age_gate").remove();$("body").append(response);get_popup_data(action);}});};$('body').on('click','button[type=submit]',function(e){e.preventDefault();$('button[type=submit]').attr('disabled',true);var form=$(this).closest('form');setTimeout(function(){form.submit();},100);});if(language_code==='en'){for(var i=0;i<$('a').length;i++){var link=$('a').eq(i).prop('href');var help_link="/help";if(link.indexOf(help_link)!==-1){$('a').eq(i).prop('target','_blank');}}}
$('body').on('mouseenter','.top-navigation li',function(){var $this=$(this);var width=($this.width()-30)/100;var pos=$this.position().left-105;$('.top-navigation .tab-decoration').css('transition','all 450ms');$('.top-navigation .tab-decoration').css('transform','translateX('+pos+'px)'+'scale('+width+',1)');$('.top-navigation .tab-decoration').css('opacity','1');});$('body').on('mouseleave','.top-navigation li',function(){var $this=$(this);var active_tab=$('.top-navigation .active').closest("li");if(active_tab.length>0){var width=(active_tab.width()-30)/100;var pos=active_tab.position().left-105;$('.top-navigation .tab-decoration').css('transform','translateX('+pos+'px)'+'scale('+width+',1)');}
else{$('.top-navigation .tab-decoration').css('opacity','0');}});